### ISSUE TITLE
gen_config generates unphysical configurations with large rij

### ISSUE THREAD

**Issue by HuangJianxiang-SJTU** [HallandSantiso-NCSU/Parallel-DMD-for-biomolecules#2]
Thanks for making this package available. I attended the lecture of Prof. Carol Hall and Keith Gubbins several years ago and it was really impressive.

The problem with the gen_config code is that it generates unreasonable structures, and it pops out "error in residue". In my opinion,  1, it takes quite long to complete the generation of configurations. 2, it generates unreasonable structures. 

So there is a bug regarding the gen_config code. My another idea is that generating the start configurations is better to be done in a more friendly way. It might be more convenient to use other packages like packmol for the packing of peptides in a given box. I am trying to write a script to do the gen_config part and maybe make use of packmol to complete the model construction.

**Comment by HuangJianxiang-SJTU** [comment]
I tried simpler peptides and it works fine. I think I need to do more testing. I managed to run DMD using this package. Thanks for making it available.

**Comment by HallandSantiso-NCSU** [comment]
Hi HuangJiianXiangZju,

I am sorry that I don't reply you earlier. I used a different email to
register for this account and had not checked regularly. Would you mind if
I ask how I should call you?

Thank you very much for giving it a try. I am the admin of the github page
but I am not the author. I am having problem with running the package
myself. Can we discuss further about it? I would love to here in more
details from you such as: what is your peptides, what conditions you ran
the simulation in, on what type of CPU, GPU? My major email is
***@***.*** I would not miss your reply if you give me a response
using this email address. Thank you very much.

Best,
Van Nguyen



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/27/21,
04:09:35 PM

**Comment by HuangJianxiang-SJTU** [comment]
Hi, Nguyen

Just call me Jim.

I get it work smoothly after many trials. Just be careful with all the variebles. My steps are as follows:
Step 0. Set the identity.input identity2.input. Peptide sequence is YNDFGNY.
Step 1. Set the boxl value in gen_config_random-SQZ.f90 and the following:
      parameter(nb=28)          ! number of beads
      parameter(nb2=27)         ! number of beads without glycines
      parameter(chnln=7)         ! chain length
      parameter(nc=24)          ! chain number
      parameter(nop=nb*nc)      !total number of beads
      parameter(nop2=nb2*nc)    !total number of beads minus glycines
        integer nb3,nb4,chnln2,nc2,nop3,nop4
      parameter(nb3=28)         ! number of beads
      parameter(nb4=27)         ! number of beads without glycines
      parameter(chnln2=7)        ! chain length
      parameter(nc2=24)
Step2. ifort gen_config_random-SQZ.f90 -o genconf; ./genconf (Note that gfortran can not compile the genconf and Intel fortran compiler will do)
 
Step3. Copy all the run0000.* files under the results directory of genconf to the upper results directory; similarly, Copy all the parameter files under the parameters directory of genconf to the upper parameters directory.
 
Step4. cd to the code directory and Set the boxl value in inputinfo.f
 
Step5.
mpif90 -Os -xAVX -no-prec-div -r8 -arch host -align dcommons -g -traceback -Dchaptype=1 -Dnop1=648 -Dnop2=648 -Dchnln1=7 -Dchnln2=7 -Dnumbeads1=27 -Dnumbeads2=27 -Dnumbin=20000 -Dn_wrap=2 -Ddebugging -Dcanon -Drunr -o ../dmd main.F90

Jim

**Comment by huangjianxiangzju** [comment]
I get it work smoothly after many trials. My steps are as follows:

Step 0. Set the identity.input identity2.input. Peptide sequence is YNDFGNY.

Step 1. Set the boxl value in&nbsp;gen_config_random-SQZ.f90 and the following:&nbsp;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parameter(nb=28) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;! number of beads

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parameter(nb2=27) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;! number of beads without glycines

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parameter(chnln=7) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;! chain length

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parameter(nc=24) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;! chain number&nbsp;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parameter(nop=nb*nc) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;!total number of beads

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parameter(nop2=nb2*nc) &nbsp;&nbsp;&nbsp;!total number of beads minus glycines

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;integer nb3,nb4,chnln2,nc2,nop3,nop4

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parameter(nb3=28) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;! number of beads

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parameter(nb4=27) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;! number of beads without glycines

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parameter(chnln2=7) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;! chain length

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parameter(nc2=24)

Step2. ifort&nbsp;gen_config_random-SQZ.f90&nbsp;-o genconf; ./genconf (Note that gfortran can not compile the genconf and Intel fortran compiler will work)

&nbsp;

Step3. Copy all the run0000.* files under the results directory of genconf to the upper results directory; similarly,&nbsp;Copy all the&nbsp;parameter&nbsp;files under the&nbsp;parameters directory of genconf to the upper&nbsp;parameters directory.&nbsp;

&nbsp;

Step4. cd to the code directory and&nbsp;Set the boxl value in&nbsp;inputinfo.f&nbsp;

&nbsp;

Step5.

mpif90 -Os -xAVX -no-prec-div -r8 -arch host -align dcommons -g -traceback -Dchaptype=1 -Dnop1=648 -Dnop2=648 -Dchnln1=7 -Dchnln2=7 -Dnumbeads1=27 -Dnumbeads2=27 -Dnumbin=20000 -Dn_wrap=2 -Ddebugging -Dcanon -Drunr -o ../dmd main.F90




&nbsp;&nbsp;

**Comment by HallandSantiso-NCSU** [comment]
Hi Jim (if you don't mind I call you by Jim),

Thank you so much for your feedback. I understand how busy you are and that
makes me even more appreciative that you tried our codes. It is crazy busy
on my side too so I am sorry if it took me a few days to reply. How many
cores do you run the parallel code with? Can you share with me your
submission script in which you specified number of core, number of
processor, MPI commands? In addition, how long did it take to finish 1
billion collisions on your cluster? I am having a problem running this code
on a HPC system. The simulation could never get out of the MPI_finalize to
move on to the next loop. Your feedback is a great help

All the best,
Van Nguyen


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality7&>
Sender
notified by Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality7&>
09/29/21,
09:31:54 PM

**Comment by HuangJianxiang-SJTU** [comment]
Hi&nbsp;Nguyen


Yeah, just call me Jim. I think the MPI finalize will exit only when I use nodes=1:ppn=2. I can run 200 billion collisions in four days and the system consists of ~1600 beads, which I think is fast enough.&nbsp;
Right now, if I use more nodes or threads for the parallel computing of the DMD code, it won't exit at all. It's not a serious problem because I can always kill the program if it finish and do not exit.
I think I will need to do more tests about the optimal nodes and ppn setting.&nbsp;
If you want to use the for loop for a series of running, I suggest you try&nbsp;nodes=1:ppn=2. I paste all the content of my pbs file below:




#!/bin/bash


#PBS -N dmd
#PBS -j oe
#PBS -q sugon
#PBS -l nodes=1:ppn=2
#PBS -l walltime=2400:00:00




cd $PBS_O_WORKDIR
NP=`cat $PBS_NODEFILE | wc -l`
NN=`cat $PBS_NODEFILE | sort | uniq | tee nodes.$$ | wc -l`
#ulimit -n 2000&nbsp; # Enable it when more than 1024 CPU cores are requested
cat $PBS_NODEFILE &gt; nodefile.$$


source /public/software/profile.d/compiler_intel-compiler-2017.5.239.sh
source /public/software/profile.d/mpi_openmpi-intel-2.1.2.sh
source /public/software/profile.d/mathlib_fftw-intelmpi-3.3.7_float.sh


cd ../code


mv ../qfile/nodefile.$$ ..
mv ../qfile/nodes.$$ ..


cd ..


temps=' 035 030 028 026 024 022'&nbsp;
for i in $temps
do mpirun -machinefile nodefile.$$ -n $NP&nbsp; ./dmd < temp_$i &gt; out_$i
done






#for i in {1..20}
#do mpirun -machinefile nodefile.$$ -n $NP&nbsp; ./dmd < temp_018 &gt; out_018_$i wait
#done


echo "Finished dmd run at" `date`
rm -rf nodefile.$$
rm -rf nodes.$$

**Comment by HuangJianxiang-SJTU** [comment]
please not that I use&nbsp;temps=' 035 030 028 026 024 022' because I run the previous 050 045 040 and I tried the for loop. So you may want to change this part.&nbsp;

**Comment by HallandSantiso-NCSU** [comment]
Dear Jim,

I tried to run with 2 ppn and it worked. However, the loop still doesn't
get finalized if the ppn is larger than 2. Can you please help me by
running with 4 ppn on the same node? Thank you so much.

Best,
Van



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
Sender
notified by Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
09/30/21,
01:08:46 PM

**Comment by HuangJianxiang-SJTU** [comment]
Dear Van


I think it is very likely that the code need to be hacked in order to have the MPI finalized. So, running with ppn: 4 may take some effort as I am not familiar with the Fortran parallel computing. I read the future work&nbsp;(Chapter 8) of Yiming's PhD dissertation&nbsp;and I read the plan to introduce parallelization into the DMD code. Below are two references I copied from that chapter about the implementation of the so called&nbsp;“event-based decomposition”. Meanwhile, I am not sure if it is possible to not change any code and run with ppn: 4. I may spend some time on this but I am not sure to say that the problem will be solved soon. It may take quite some time. Still, ppn:2 is fast enough for many systems I think.


2.&nbsp;Khan, M. A., Herbordt, M. C. (2011) Parallel discrete molecular dynamics simulation with&nbsp;speculation and in-order commitment. J. Comput. Phys. 230, 6535-6582
3.&nbsp;Shirvanyants, D., Ding, Feng., Tsao, D., Ramachandran, S., Dokholyan, N. V. (2012)&nbsp;Discrete Molecular Dynamics: An Efficient And Versatile Simulation Method For Fine&nbsp;Protein Characterization. J. Phys. Chem. B 116, 8375-8382&nbsp;




Best regard




Jim

**Comment by HuangJianxiang-SJTU** [comment]
Dear Van


Any idea what the parameter files under the parameterseq directory are?&nbsp;&nbsp;




Best regards


Jim

**Comment by HallandSantiso-NCSU** [comment]
Dear Jim,

My apology for the late reply. I am volunteering to help with organizing
the Future Leader Symposium, therefore I have been busy for the last 2
weeks and totally forgot to respond. Tbh I saw your emails and told myself
that I would respond but completely slipped my mind. I am very sorry again.
The event will end on Monday so I will get back to you as soon as possible.

Best,

Van Nguyen



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/24/21,
12:38:58 PM

**Comment by HuangJianxiang-SJTU** [comment]
Dear van
Never mind. With the information contained in the published papers, I think I know what the files under the several directories contain.&nbsp;
Best regards&nbsp;





------------------ Original ------------------
From: HallandSantiso-NCSU ***@***.***&gt;
Date: Mon, Oct 25, 2021 0:43 AM
To: HallandSantiso-NCSU/Parallel-DMD-for-biomolecules ***@***.***&gt;
Cc: huangjianxiangzju ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [HallandSantiso-NCSU/Parallel-DMD-for-biomolecules] gen_configgenerates unphysical configurations with large rij (#2)

**Comment by HallandSantiso-NCSU** [comment]
Thank you Jim. Please let me know if you have any other questions or
suggestions. I will try to reply as soon as possible. This month and early
Nov is very busy for me. I apologize and appreciate that you are trying our
codes.

Best,

Van Nguyen



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/24/21,
12:46:52 PM

**Comment by HuangJianxiang-SJTU** [comment]
Ok. I will. Thanks for your reply during these busy weeks.&nbsp;
Jim





------------------ Original ------------------
From: HallandSantiso-NCSU ***@***.***&gt;
Date: Mon, Oct 25, 2021 0:48 AM
To: HallandSantiso-NCSU/Parallel-DMD-for-biomolecules ***@***.***&gt;
Cc: huangjianxiangzju ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [HallandSantiso-NCSU/Parallel-DMD-for-biomolecules] gen_configgenerates unphysical configurations with large rij (#2)
